export type OpportunityStatus = "unclaimed" | "active" | "snoozed" | "won" | "lost" | "do_not_contact";
export type TimelineItem = { id: string; label: string; detail: string; at: string };
export type Opportunity = {
  id: string; customerName: string; phone: string; email?: string; city: string; source: string; summary: string;
  priority: "urgent" | "high" | "normal" | "low"; stage: string; ownerName?: string; status: OpportunityStatus;
  createdAt: string; submittedAt?: string; nextActionAt?: string; nextActionTitle?: string; nextActivityAt?: string; lastInteractionAt?: string; lastContactedAt?: string; preferred?: string; warning?: string;
  unsuccessfulAttempts?: number; closeReason?: string; auditAt?: string; auditConfirmedAt?: string; calendarSyncStatus?: "pending" | "synced" | "failed";
  purchaseLinkName?: string; handoffStatus?: "awaiting_shopify_link" | "linked"; timeline: TimelineItem[];
  consideringFor?: string[]; safetyConcerns?: string[]; immediateSafetyConcern?: boolean; expressedInterest?: string; preferredContactDay?: string; preferredContactPeriod?: string;
};

const now = new Date("2026-08-02T07:30:00.000Z");
const at = (hour: number, minute = 0, dayOffset = 0) => { const date = new Date(now); date.setDate(date.getDate() + dayOffset); date.setHours(hour, minute, 0, 0); return date.toISOString(); };
const minutesFromNow = (minutes: number) => new Date(now.getTime() + minutes * 60_000).toISOString();
const history = (id: string, label: string, detail: string, date: string): TimelineItem[] => [{ id: `${id}-timeline`, label, detail, at: date }];

export const initialOpportunities: Opportunity[] = [
  { id: "lead-1", customerName: "Mrs. Kavita Sharma", phone: "+91 98765 43210", email: "kavita@example.com", city: "Gurugram", source: "Jotform", summary: "Bathroom safety assessment for her mother; daughter joins calls after 11 AM.", consideringFor: ["Senior parent / grandparent living in the same home"], safetyConcerns: ["Bathroom slips or falls", "Night-time bathroom use"], immediateSafetyConcern: true, expressedInterest: "Book a bathroom safety assessment", preferredContactDay: "Tomorrow", preferredContactPeriod: "Morning", priority: "urgent", stage: "New enquiry", status: "unclaimed", createdAt: at(8, 12), submittedAt: at(8, 12), preferred: "11:00 AM–1:00 PM", warning: "Waiting for pickup", timeline: history("1", "Jotform enquiry received", "Assessment interest recorded; no appointment created.", at(8, 12)) },
  { id: "lead-2", customerName: "Mr. Anand Iyer", phone: "+91 98110 24816", city: "Delhi", source: "Jotform", summary: "Exploring fall detection for both parents. Asked about installation timeline.", consideringFor: ["Senior parent / grandparent living away"], safetyConcerns: ["No one nearby during emergency", "Need emergency alert system"], immediateSafetyConcern: false, expressedInterest: "Understand the EyEagle safety kit", preferredContactDay: "This weekend", preferredContactPeriod: "Afternoon", priority: "high", stage: "New enquiry", status: "unclaimed", createdAt: at(9, 5), submittedAt: at(9, 5), preferred: "After 2:00 PM", timeline: history("2", "Jotform enquiry received", "Product interest recorded; no sales task created.", at(9, 5)) },
  { id: "lead-3", customerName: "Colonel R. S. Bedi", phone: "+91 99718 10422", city: "Gurugram", source: "Referral", summary: "Follow up after senior-living workshop. Interested in two bathrooms.", consideringFor: ["Myself"], safetyConcerns: ["Need bathroom grab bars / support"], expressedInterest: "Book a bathroom safety assessment", preferredContactDay: "Tomorrow", preferredContactPeriod: "Afternoon", priority: "high", stage: "Contacting", status: "active", ownerName: "Asha Mehta", createdAt: at(12, 0, -4), lastInteractionAt: at(16, 40, -1), nextActionAt: minutesFromNow(-35), nextActionTitle: "Retry call", warning: "Overdue", unsuccessfulAttempts: 1, timeline: history("3", "No answer", "Called once; another attempt was scheduled.", at(16, 40, -1)) },
  { id: "lead-4", customerName: "Neena Kapoor", phone: "+91 98990 72514", city: "Noida", source: "Jotform", summary: "Audit confirmed for the ground-floor bathroom. Son will meet the auditor.", consideringFor: ["Senior parent / grandparent living in the same home"], safetyConcerns: ["Bathroom slips or falls"], immediateSafetyConcern: true, expressedInterest: "Book a bathroom safety assessment", preferredContactDay: "Day After Tomorrow", preferredContactPeriod: "Morning", priority: "normal", stage: "Audit scheduled", status: "active", ownerName: "Asha Mehta", createdAt: at(10, 18, -5), lastInteractionAt: at(14, 0, -1), nextActionAt: at(11, 0, 1), nextActionTitle: "Bathroom audit", auditAt: at(11, 0, 1), auditConfirmedAt: at(14, 0, -1), calendarSyncStatus: "synced", timeline: history("4", "Audit appointment confirmed", "Customer confirmed the date and time; Calendar synced.", at(14, 0, -1)) },
  { id: "lead-5", customerName: "Meera Nair", phone: "+91 99201 34882", city: "Delhi", source: "Jotform", summary: "Daughter is comparing packages for parents in Vasant Kunj.", expressedInterest: "Get pricing details", priority: "normal", stage: "Awaiting purchase", status: "active", ownerName: "Asha Mehta", createdAt: at(12, 0, -8), lastInteractionAt: at(14, 10, -2), nextActionAt: minutesFromNow(180), nextActionTitle: "Purchase review", purchaseLinkName: "Essential Safety Package", timeline: history("5", "Purchase link sent", "Essential Safety Package via WhatsApp.", at(14, 10, -2)) },
  { id: "lead-6", customerName: "Sanjay Malhotra", phone: "+91 98104 11029", city: "Noida", source: "Phone", summary: "Audit completed; family asked for a call after their travel.", priority: "normal", stage: "Snoozed", status: "snoozed", ownerName: "Asha Mehta", createdAt: at(12, 0, -11), lastInteractionAt: at(12, 15, -3), nextActionAt: at(10, 0, 5), nextActionTitle: "Return to customer", timeline: history("6", "Snoozed", "Family returns next week; review is scheduled.", at(12, 15, -3)) },
  { id: "lead-7", customerName: "Dr. Leela Menon", phone: "+91 98911 60555", city: "Delhi", source: "Referral", summary: "Customer confirmed the purchase after the audit.", priority: "normal", stage: "Converted", status: "won", ownerName: "Asha Mehta", createdAt: at(12, 0, -14), lastInteractionAt: at(17, 30, -1), handoffStatus: "awaiting_shopify_link", warning: "Awaiting Shopify link", timeline: history("7", "Marked sold", "Pending handoff created; payment not yet confirmed.", at(17, 30, -1)) },
  { id: "lead-8", customerName: "Vikram Khanna", phone: "+91 99100 78220", city: "Delhi", source: "Jotform", summary: "Asked about pricing but decided not to proceed.", priority: "low", stage: "Not proceeding", status: "lost", ownerName: "Asha Mehta", createdAt: at(9, 0, -16), lastInteractionAt: at(13, 0, -4), closeReason: "Price", timeline: history("8", "Opportunity closed", "Not proceeding — price.", at(13, 0, -4)) },
];

export const approvedPurchaseLinks = [
  { id: "link-essential", name: "Essential Safety Package", url: "https://eyeagle.in/buy/essential" },
  { id: "link-complete", name: "Complete Home Safety Package", url: "https://eyeagle.in/buy/complete" },
  { id: "link-audit", name: "Paid Bathroom Audit", url: "https://eyeagle.in/buy/audit" },
];

// Compatibility exports for the earlier prototype screens that are no longer mounted.
export type Lead = Opportunity;
export type Activity = { id: string; leadId: string; customerName: string; phone: string; type: string; title: string; scheduledStart: string; status: "scheduled" | "overdue" | "completed"; note?: string };
export const stages = ["New enquiry", "Contacting", "Audit scheduled", "Awaiting purchase", "Snoozed", "Converted", "Not proceeding", "Do not contact"];
